### PR TITLE
Update GitHub actions workflows

### PR DESCRIPTION
**Pull request by ggabernet**
# nf-core/viralrecon pull request

Many thanks for contributing to nf-core/viralrecon!

Please fill in the appropriate checklist below (delete whatever is not relevant).
These are the most common things requested on pull requests (PRs).

## PR checklist

- [ ] This comment contains a description of changes (with reason)
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If necessary, also make a PR on the [nf-core/viralrecon branch on the nf-core/test-datasets repo](https://github.com/nf-core/test-datasets/pull/new/nf-core/viralrecon)
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Make sure your code lints (`nf-core lint .`).
- [ ] Documentation in `docs` is updated
- [ ] `CHANGELOG.md` is updated
- [ ] `README.md` is updated

**Learn more about contributing:** [CONTRIBUTING.md](https://github.com/nf-core/viralrecon/tree/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by drpatelh** [comment]
Is this now ready to merge @ggabernet ?

**Comment by drpatelh** [comment]
We should be able to remove the 4GB instance requirement now and the garbage collection stuff too? Or will that only work if the jobs are submitted directly via Tower?

**Comment by ggabernet** [comment]
that will only work via tower, as far as I understood. We could add it to the `awsbatch` profile in our case. I will have time to test this out this weekend

**Comment by drpatelh** [comment]
Tests are going to run on `master` again anyway so merging.

**Pull request merged**
