### PR TITLE
fix merge TEMPLATE

### PR DESCRIPTION
**Pull request by maxulysse**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/viralrecon/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/viralrecon _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by maxulysse** [comment]
Should replace #331

**Review by saramonzon — APPROVED** [review]

**Comment by maxulysse** [comment]
@saramonzon I can't seem to get some of the Nanopore test to pass, any idea what could be the issue?
I'm thinking it's a staging issue of the input files, but I'm having issues to reproduce locally

**Comment by robsyme** [comment]
Could the nanopore tests be failing due to insufficient disk space? These test runner instances are usually minimally spec'd, and the nanopore fast5 dataset is 633.8 MiB. Do we know how much disk space we get for each workflow?
Edit: Looks like [14GB for each runner](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources), which should be sufficient?

**Comment by maxulysse** [comment]
Managed somehow to have just the two tests that are now failing on CI.
As you said @robsyme I'd assume space is indeed sufficient enough as well.
Reproducing them locally, if they pass, that's enough for me, and I'll merge then.
And we'll fix the tests in a future PR

**Pull request merged**
