### PR TITLE
ADD Subway map

### PR DESCRIPTION
**Pull request by maxulysse**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/viralrecon/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/viralrecon _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by jfy133** [comment]
Still some issues:

## Illumina


Misalignment of line right of Kraken


Slight misalignment of blue line to the left of SNPEff and right of ASCII



'Stage' text in legend is higher than top of the metro map zone boxes


MosDepth gap between station and text is more than other stations (however I generally am finding the text is a bit cramped, I would put a a bit more space between all labels)

_Edit: screenshots failed so removed_

**Comment by maxulysse** [comment]
> Still some issues:
> ## Illumina
> 
> Misalignment of line right of Kraken

Fixed

> 
> Slight misalignment of blue line to the left of SNPEff and right of ASCII
> 

Fixed

> 'Stage' text in legend is higher than top of the metro map zone boxes
> 

Actually no, it's perfectly aligned.

> MosDepth gap between station and text is more than other stations.

That's intentional

> (however I generally am finding the text is a bit cramped, I would put a a bit more space between all labels)

Added more space, but having issues with the border of the gray boxes

> _Edit: screenshots failed so removed_

Actually worked on the email I got from github

**Review by jfy133 — APPROVED** [review]
This approval is just from a graphic design perspective, nothing on the accuracy ;)

Last thing is BT2 line misalignment

image

But otherwise LGTM now

**Comment by drpatelh** [comment]
Feel free to merge when @jfy133 comments have been addressed! Thanks for the comments!

**Comment by jfy133** [comment]
Good to go!

**Pull request merged**
