### PR TITLE
Update multiqc & add freyja to MQC

### PR DESCRIPTION
**Pull request by Joon-Klaps**
## PR checklist

Multiqc supports the output of `Freyja demix`, it can be added to the pipeline. 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/viralrecon/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/viralrecon _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by Joon-Klaps** [comment]
The result from `nextflow run . -profile docker,test --outdir testing` looks like this. 
image

**Comment by Joon-Klaps** [comment]
@nf-core-bot fix linting

**Comment by svarona** [comment]
> The result from `nextflow run . -profile docker,test --outdir testing` looks like this. image

Maybe you can add the freyja's MQC plot to the `output.md` file for both nanopore and Illumina, it would be great!

**Comment by svarona** [comment]
Thanks a lot for these enhancements!

**Review by svarona — APPROVED** [review]

**Pull request merged**
