### PR TITLE
417 allow skipping freyja boot

### LINKED ISSUE #417: Allow skipping `freyja boot`
### Description of feature

To save some computation, it may sometimes be desirable to skip `freyja`'s bootstrapping step. 

My suggestion would be to allow using `--freyja_repeats 0`. At the moment, using it like this throws an internal error from freyja. 
But maybe `viralrecon` could interpret 0 (or any negative number, for that matter) as meaning "don't run the bootstrap step".

In fact, it may be worth considering `--freyja_repeats 0` as the default, in case those processing clinical isolates forget to do `--skip_freyja` and end up spending a lot of unnecessary compute time bootstrapping.

I guess an alternative would be to add a new option `--skip_freyja_boot`.

### PR DESCRIPTION
**Pull request by Joon-Klaps**
## PR checklist

Solves issue #417, allow freyja boostrapping module to be skipped if specified by the user.  + version bump of modules. 

- [X] This comment contains a description of changes (with reason).
- [X] If you've fixed a bug or added code that should be tested, add tests!
- [X] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/viralrecon/tree/master/.github/CONTRIBUTING.md)
- [ ] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [X] Usage Documentation in `docs/usage.md` is updated.
- [X] Output Documentation in `docs/output.md` is updated.
- [X] `CHANGELOG.md` is updated.
- [X] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by Joon-Klaps** [comment]
Waiting for https://github.com/nf-core/modules/pull/5555 to be merged

**Comment by Joon-Klaps** [comment]
CI fails because of linting for a subworkflow I haven't touched 😕

**Comment by maxulysse** [comment]
> CI fails because of linting for a subworkflow I haven't touched 😕

Yeah, that's a tools issue unfortunately, updating this particular subworkflow should fix the issue.
sorry about that

**Review by svarona — APPROVED** [review]
ILGTM! Another issue fixed! 🥳

**Comment by maxulysse** [comment]
Yeah, I feel like we're getting closer and closer to a release

**Pull request merged**
