### PR TITLE
Refine SRA functionality

### PR DESCRIPTION
**Pull request by drpatelh**
# nf-core/viralrecon pull request

Many thanks for contributing to nf-core/viralrecon!

Please fill in the appropriate checklist below (delete whatever is not relevant).
These are the most common things requested on pull requests (PRs).

## PR checklist

- [ ] This comment contains a description of changes (with reason)
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If necessary, also make a PR on the [nf-core/viralrecon branch on the nf-core/test-datasets repo](https://github.com/nf-core/test-datasets/pull/new/nf-core/viralrecon)
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [x] Make sure your code lints (`nf-core lint .`).
- [x] Documentation in `docs` is updated
- [ ] `CHANGELOG.md` is updated
- [x] `README.md` is updated

**Learn more about contributing:** [CONTRIBUTING.md](https://github.com/nf-core/viralrecon/tree/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by drpatelh** [comment]
Something weird going on with the `diff` in `main.nf`...just a massive replacement of code.

**Comment by JoseEspinosa** [comment]
Tests are failing since no `txt` file is generated by the process `CHECK_SAMPLESHEET` when there are any declared files to download in the `samplesheet`, we can solve this by at least this two ways:

* declaring the output channel ch_samplesheet_sra as `optional true` 
* creating an empty `txt` file when no files to download are declared

Actually, right now we are not using this channel but we should implement the code to allow the user to access SRA info and/or warnings output by `check_samplesheet.py`

**Comment by JoseEspinosa** [comment]
The order of columns output by `check_samplesheet.py` to the `sra_runinfo.txt` file does not match the header. The fix will be to modify line 191:

`for col in sraRunInfoHeader:` to `for col in sorted(sraRunInfoHeader):`

This way data columns will match the order of the header

**Comment by svarona** [comment]
Merged PR #50

**Pull request merged**
